# Generated by Django 4.2.3 on 2023-07-28 08:11

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor) -> None:
    from django.core.management import call_command

    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("library", "0008_alter_book_daily_fee_alter_book_inventory"),
        ("user", "0003_remove_user_username_alter_user_first_name_and_more"),
    ]

    operations = [RunPython(func, reverse_func)]
